In [2]:
import torch
import numpy as np
from torch.distributions import Categorical
from torch.optim import Adam
from torch.nn import MSELoss
from torch import nn 

In [25]:
# Create a categorical distribution with given probabilities
prob = torch.tensor([2.0, 1.0, 0.1])

m = Categorical(logits=prob)

x = m.sample()  # sample from the distribution

print(m.probs)
print(x)


tensor([0.6590, 0.2424, 0.0986])
tensor(1)


In [27]:
num = np.array([1.0, 2.0, 3.0])
ten = torch.tensor([1.0, 2.0, 3.0])
print(num)
print(ten)

[1. 2. 3.]
tensor([1., 2., 3.])


In [ ]:
# implement linear regression
## generate noisy data 
## class regresion 
### init 
### forward 

x = torch.rand(100, 1) * 10 
y = 2*x+3+torch.rand(100, 1)*10

class regression(nn.Module):
    def __init__(self,input_size,output):
        super(regression,self).__init__()
        self.regression  = nn.Linear(input_size,output)
        
    def forward(self,input):
        return self.regression(input)
        
def train(epoch=1000):
    model = regression(1,1)
    optimizer = Adam(params=model.parameters(),lr = 1e-2)

    def loss_func(prediction,Y):
        return nn.MSELoss(prediction,Y)    

    for i in range(epoch):

        X = model(x)
        loss = loss_func(X,Y=y)
        loss.backward()
        optimizer.step()




## Beginner Exercises

### Create tensors
- Create a tensor of shape (3, 4) filled with ones.
- Create a tensor of shape (2, 3) with random values between 0 and 1.
- Create a tensor of shape (5,) with integers from 10 to 14.

### Reshaping
- Given a tensor of shape (6,), reshape it to (2, 3).
- Flatten a (2, 3, 4) tensor into (24,).

## Indexing & slicing
- From a (4, 5) tensor of random numbers, extract the 2nd row.
- Extract the last column.
- Extract a 2x2 submatrix from the top-left corner.

In [53]:
one_tensor = torch.ones(3,4)
rand_tensor = torch.rand(2,3)
int_tensor = torch.randint(10,14,(5,))

print(int_tensor)

reshape_1 = torch.ones(6,).reshape(2,3)
flatten = torch.ones(2,3,4).flatten()
torch_rand = torch.rand(4,5)[1:2,:]
torch_rand2 = torch.rand(4,5)
print(torch_rand.shape)
print(torch_rand2)
#print(torch_rand2[:,1:])
print(torch_rand2[:2,:2])
print(torch_rand2[3,4])
print(flatten)
print(reshape_1)

tensor([13, 12, 12, 11, 13])
torch.Size([1, 5])
tensor([[0.9941, 0.1571, 0.8375, 0.4253, 0.4684],
        [0.8820, 0.1999, 0.3000, 0.1846, 0.4069],
        [0.7500, 0.6224, 0.3362, 0.9613, 0.8089],
        [0.0788, 0.5322, 0.1632, 0.7856, 0.8573]])
tensor([[0.9941, 0.1571],
        [0.8820, 0.1999]])
tensor(0.8573)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Memory layout in PyTorch
- A tensor’s elements are stored in a 1D contiguous block of memory (flattened).
- The shape tells you how many elements are in each dimension.
- The stride tells you how to jump through that flat memory to pretend it’s multi-dimensional.
- So: Tensor = (data in flat memory) + (shape) + (stride).

In [66]:
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)

tensor3 = torch.cat((tensor1,tensor2),dim=0)
tensor4 = torch.cat((tensor1,tensor2),dim=1)

print(tensor3.shape)
print(tensor4.shape)

tensor5 = torch.rand(3,)
tensor6 = torch.rand(3,)
tensor7 = torch.rand(3,)
tensor8 = torch.rand(3,)
tensor9 = torch.rand(3,)
tensor10 = torch.stack((tensor5,tensor6,tensor7,tensor8,tensor9), dim=0)
print(tensor10.shape)

tensor11 = torch.rand(3,1)
tensor12 = torch.rand(1,4)
tensor13 = tensor11+tensor12
print(tensor13.shape)

torch.Size([4, 3])
torch.Size([2, 6])
torch.Size([5, 3])
torch.Size([3, 4])


PyTorch doesn’t manually loop over rows/cols.
It calls highly optimized BLAS/cuBLAS kernels.
Optimization techniques include:
    - Vectorization (SIMD on CPU, warps on GPU)
    - Cache tiling
    - Loop unrolling
    - Specialized hardware (Tensor Cores)

In [81]:
int_tensor = torch.randint(10,14,(20,))
tensor = torch.masked_select(int_tensor,int_tensor>11)
 

transpose = torch.rand(3,4)
transpose2 = transpose.T

shape = torch.rand((2, 3, 4))
reshape = shape.reshape(4, 2, 3)
print(shape)
print(reshape)


mean = torch.rand((3, 5))
means = mean.mean(dim=1)
means

indexs = torch.rand((10))
index = torch.argmax(indexs).item()
index

tensor([[[0.2824, 0.5962, 0.5751, 0.4169],
         [0.4670, 0.6339, 0.5308, 0.7575],
         [0.2844, 0.7697, 0.3408, 0.6234]],

        [[0.1054, 0.2061, 0.9190, 0.6583],
         [0.6751, 0.7465, 0.2917, 0.3791],
         [0.3228, 0.3365, 0.6288, 0.8772]]])
tensor([[[0.2824, 0.5962, 0.5751],
         [0.4169, 0.4670, 0.6339]],

        [[0.5308, 0.7575, 0.2844],
         [0.7697, 0.3408, 0.6234]],

        [[0.1054, 0.2061, 0.9190],
         [0.6583, 0.6751, 0.7465]],

        [[0.2917, 0.3791, 0.3228],
         [0.3365, 0.6288, 0.8772]]])


8

In [87]:
mat1 = torch.rand(10,2,5)
mat2 = torch.rand(10,5,3)

mat3 = mat1 @ mat2

mat3

tensor([[[0.9774, 1.3048, 0.9484],
         [1.0400, 1.7563, 0.9133]],

        [[0.9161, 1.6865, 1.2889],
         [1.3316, 1.9903, 1.6091]],

        [[0.5159, 1.1496, 1.0573],
         [0.5906, 0.8205, 1.1642]],

        [[1.1881, 1.0514, 1.3172],
         [2.0048, 2.0108, 2.7825]],

        [[1.2100, 0.7351, 0.8591],
         [1.0401, 1.0771, 1.0237]],

        [[1.4483, 1.1131, 1.4766],
         [1.8192, 1.5580, 1.5208]],

        [[2.3495, 2.2897, 2.0965],
         [1.0560, 0.9122, 0.8522]],

        [[1.0321, 1.3409, 1.2096],
         [0.8904, 1.3485, 1.5040]],

        [[1.6036, 1.6470, 1.1457],
         [1.2831, 1.4632, 1.0235]],

        [[0.6462, 1.7841, 1.2301],
         [0.5728, 1.0189, 0.9515]]])