In [2]:
import torch
import numpy as np
from torch.distributions import Categorical
from torch.optim import Adam
from torch.nn import MSELoss
from torch import nn 

In [25]:
# Create a categorical distribution with given probabilities
prob = torch.tensor([2.0, 1.0, 0.1])

m = Categorical(logits=prob)

x = m.sample()  # sample from the distribution

print(m.probs)
print(x)


tensor([0.6590, 0.2424, 0.0986])
tensor(1)


In [27]:
num = np.array([1.0, 2.0, 3.0])
ten = torch.tensor([1.0, 2.0, 3.0])
print(num)
print(ten)

[1. 2. 3.]
tensor([1., 2., 3.])


In [ ]:
# implement linear regression
## generate noisy data 
## class regresion 
### init 
### forward 

x = torch.rand(100, 1) * 10 
y = 2*x+3+torch.rand(100, 1)*10

class regression(nn.Module):
    def __init__(self,input_size,output):
        super(regression,self).__init__()
        self.regression  = nn.Linear(input_size,output)
        
    def forward(self,input):
        return self.regression(input)
        
def train(epoch=1000):
    model = regression(1,1)
    optimizer = Adam(params=model.parameters(),lr = 1e-2)

    def loss_func(prediction,Y):
        return nn.MSELoss(prediction,Y)    

    for i in range(epoch):

        X = model(x)
        loss = loss_func(X,Y=y)
        loss.backward()
        optimizer.step()




## Beginner Exercises

### Create tensors
- Create a tensor of shape (3, 4) filled with ones.
- Create a tensor of shape (2, 3) with random values between 0 and 1.
- Create a tensor of shape (5,) with integers from 10 to 14.

### Reshaping
- Given a tensor of shape (6,), reshape it to (2, 3).
- Flatten a (2, 3, 4) tensor into (24,).

## Indexing & slicing
- From a (4, 5) tensor of random numbers, extract the 2nd row.
- Extract the last column.
- Extract a 2x2 submatrix from the top-left corner.

In [53]:
one_tensor = torch.ones(3,4)
rand_tensor = torch.rand(2,3)
int_tensor = torch.randint(10,14,(5,))

print(int_tensor)

reshape_1 = torch.ones(6,).reshape(2,3)
flatten = torch.ones(2,3,4).flatten()
torch_rand = torch.rand(4,5)[1:2,:]
torch_rand2 = torch.rand(4,5)
print(torch_rand.shape)
print(torch_rand2)
#print(torch_rand2[:,1:])
print(torch_rand2[:2,:2])
print(torch_rand2[3,4])
print(flatten)
print(reshape_1)

tensor([13, 12, 12, 11, 13])
torch.Size([1, 5])
tensor([[0.9941, 0.1571, 0.8375, 0.4253, 0.4684],
        [0.8820, 0.1999, 0.3000, 0.1846, 0.4069],
        [0.7500, 0.6224, 0.3362, 0.9613, 0.8089],
        [0.0788, 0.5322, 0.1632, 0.7856, 0.8573]])
tensor([[0.9941, 0.1571],
        [0.8820, 0.1999]])
tensor(0.8573)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Memory layout in PyTorch
- A tensor’s elements are stored in a 1D contiguous block of memory (flattened).
- The shape tells you how many elements are in each dimension.
- The stride tells you how to jump through that flat memory to pretend it’s multi-dimensional.
- So: Tensor = (data in flat memory) + (shape) + (stride).

In [66]:
tensor1 = torch.rand(2,3)
tensor2 = torch.rand(2,3)

tensor3 = torch.cat((tensor1,tensor2),dim=0)
tensor4 = torch.cat((tensor1,tensor2),dim=1)

print(tensor3.shape)
print(tensor4.shape)

tensor5 = torch.rand(3,)
tensor6 = torch.rand(3,)
tensor7 = torch.rand(3,)
tensor8 = torch.rand(3,)
tensor9 = torch.rand(3,)
tensor10 = torch.stack((tensor5,tensor6,tensor7,tensor8,tensor9), dim=0)
print(tensor10.shape)

tensor11 = torch.rand(3,1)
tensor12 = torch.rand(1,4)
tensor13 = tensor11+tensor12
print(tensor13.shape)

torch.Size([4, 3])
torch.Size([2, 6])
torch.Size([5, 3])
torch.Size([3, 4])


PyTorch doesn’t manually loop over rows/cols.
It calls highly optimized BLAS/cuBLAS kernels.
Optimization techniques include:
    - Vectorization (SIMD on CPU, warps on GPU)
    - Cache tiling
    - Loop unrolling
    - Specialized hardware (Tensor Cores)

In [81]:
int_tensor = torch.randint(10,14,(20,))
tensor = torch.masked_select(int_tensor,int_tensor>11)
 

transpose = torch.rand(3,4)
transpose2 = transpose.T

shape = torch.rand((2, 3, 4))
reshape = shape.reshape(4, 2, 3)
print(shape)
print(reshape)


mean = torch.rand((3, 5))
means = mean.mean(dim=1)
means

indexs = torch.rand((10))
index = torch.argmax(indexs).item()
index

tensor([[[0.2824, 0.5962, 0.5751, 0.4169],
         [0.4670, 0.6339, 0.5308, 0.7575],
         [0.2844, 0.7697, 0.3408, 0.6234]],

        [[0.1054, 0.2061, 0.9190, 0.6583],
         [0.6751, 0.7465, 0.2917, 0.3791],
         [0.3228, 0.3365, 0.6288, 0.8772]]])
tensor([[[0.2824, 0.5962, 0.5751],
         [0.4169, 0.4670, 0.6339]],

        [[0.5308, 0.7575, 0.2844],
         [0.7697, 0.3408, 0.6234]],

        [[0.1054, 0.2061, 0.9190],
         [0.6583, 0.6751, 0.7465]],

        [[0.2917, 0.3791, 0.3228],
         [0.3365, 0.6288, 0.8772]]])


8

In [87]:
mat1 = torch.rand(10,2,5)
mat2 = torch.rand(10,5,3)

mat3 = mat1 @ mat2

mat3

tensor([[[0.9774, 1.3048, 0.9484],
         [1.0400, 1.7563, 0.9133]],

        [[0.9161, 1.6865, 1.2889],
         [1.3316, 1.9903, 1.6091]],

        [[0.5159, 1.1496, 1.0573],
         [0.5906, 0.8205, 1.1642]],

        [[1.1881, 1.0514, 1.3172],
         [2.0048, 2.0108, 2.7825]],

        [[1.2100, 0.7351, 0.8591],
         [1.0401, 1.0771, 1.0237]],

        [[1.4483, 1.1131, 1.4766],
         [1.8192, 1.5580, 1.5208]],

        [[2.3495, 2.2897, 2.0965],
         [1.0560, 0.9122, 0.8522]],

        [[1.0321, 1.3409, 1.2096],
         [0.8904, 1.3485, 1.5040]],

        [[1.6036, 1.6470, 1.1457],
         [1.2831, 1.4632, 1.0235]],

        [[0.6462, 1.7841, 1.2301],
         [0.5728, 1.0189, 0.9515]]])

In [99]:
img = torch.rand(28,28)
cron = img[7:21,7:21]
cron.flip(dims=[0])

tensor([[0.9678, 0.3931, 0.4229, 0.8600, 0.0147, 0.8094, 0.6583, 0.4485, 0.7621,
         0.8677, 0.5004, 0.0443, 0.1832, 0.9875],
        [0.8733, 0.0722, 0.8137, 0.0078, 0.9765, 0.8815, 0.8685, 0.1725, 0.3373,
         0.7381, 0.3777, 0.1789, 0.3152, 0.6220],
        [0.5609, 0.5069, 0.9005, 0.6284, 0.2629, 0.5917, 0.2279, 0.6277, 0.9347,
         0.8031, 0.0091, 0.9943, 0.8072, 0.3507],
        [0.8043, 0.6784, 0.4223, 0.2593, 0.1807, 0.0283, 0.5023, 0.8466, 0.9407,
         0.1071, 0.9327, 0.7651, 0.7674, 0.9032],
        [0.3978, 0.4939, 0.8179, 0.3565, 0.4857, 0.1751, 0.3358, 0.2068, 0.8250,
         0.3934, 0.4175, 0.6778, 0.7071, 0.7924],
        [0.9970, 0.4450, 0.0488, 0.5670, 0.9040, 0.3934, 0.6488, 0.6354, 0.9233,
         0.2874, 0.2319, 0.3145, 0.2868, 0.2744],
        [0.3561, 0.3086, 0.2197, 0.6214, 0.9387, 0.8658, 0.1999, 0.4029, 0.2960,
         0.3319, 0.2559, 0.8010, 0.7283, 0.8169],
        [0.9629, 0.9838, 0.6510, 0.0167, 0.1935, 0.6390, 0.7864, 0.9464, 0.4041,
  

In [124]:
t = torch.arange(16).view(4, 4)
rows = torch.arange(t.size(0))
cols= torch.arange(t.size(1))
t[rows,cols] = -1
t

tensor([[-1,  1,  2,  3],
        [ 4, -1,  6,  7],
        [ 8,  9, -1, 11],
        [12, 13, 14, -1]])

In [125]:
t = torch.rand(13,5)

norm = t.norm(p=1,dim=1,keepdim=True)

t_norm = t/norm
t_norm.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000])

No loop means Broadcasting most of the time 

In [126]:
from torch.nn.functional import one_hot
one_hot_m = torch.zeros(3,4)
t = torch.tensor([2,0,3])

one_hot(t,4)

eyes = torch.eye(4)
eyes[t]

tensor([[0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]])