In [29]:
import torch
import numpy as np
from torch.distributions import Categorical
from torch.optim import Adam
from torch.nn import MSELoss
from torch import nn 

In [25]:
# Create a categorical distribution with given probabilities
prob = torch.tensor([2.0, 1.0, 0.1])

m = Categorical(logits=prob)

x = m.sample()  # sample from the distribution

print(m.probs)
print(x)


tensor([0.6590, 0.2424, 0.0986])
tensor(1)


In [27]:
num = np.array([1.0, 2.0, 3.0])
ten = torch.tensor([1.0, 2.0, 3.0])
print(num)
print(ten)

[1. 2. 3.]
tensor([1., 2., 3.])


In [ ]:
# implement linear regression
## generate noisy data 
## class regresion 
### init 
### forward 

x = torch.rand(100, 1) * 10 
y = 2*x+3+torch.rand(100, 1)*10

class regression(nn.Module):
    def __init__(self,input_size,output):
        super(regression,self).__init__()
        self.regression  = nn.Linear(input_size,output)

        
    def forward(self,input):
        return self.regression(input)
        


def train(epoch=1000):
    
    model = regression(1,1)

    optimizer = Adam(params=model.parameters(),lr = 1e-2)

    def loss_func(prediction,Y):
        return nn.MSELoss(prediction,Y)    


    for i in range(epoch):

        X = model(x)
        loss = loss_func(X,Y=y)
        loss.backward()
        optimizer.step()


