In [26]:
import torch
import numpy as np
from torch.distributions import Categorical

In [25]:
# Create a categorical distribution with given probabilities
prob = torch.tensor([2.0, 1.0, 0.1])

m = Categorical(logits=prob)

x = m.sample()  # sample from the distribution

print(m.probs)
print(x)


tensor([0.6590, 0.2424, 0.0986])
tensor(1)


In [27]:
num = np.array([1.0, 2.0, 3.0])
ten = torch.tensor([1.0, 2.0, 3.0])
print(num)
print(ten)

[1. 2. 3.]
tensor([1., 2., 3.])
